/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package las.views;

/**
 *
 * @author Gimhani Uthpala
 */
public class ApplicationForm1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form ApplicationForm1
     */
    public ApplicationForm1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        newApplicantTab = new javax.swing.JPanel();
        NewApplicantDetailPanel = new javax.swing.JPanel();
        personalDetailPanel = new javax.swing.JPanel();
        RegNo = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        NIC = new javax.swing.JLabel();
        regNotext = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        nicText = new javax.swing.JTextField();
        Address = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addressText = new javax.swing.JTextArea();
        Status = new javax.swing.JLabel();
        marriedStatusRButton = new javax.swing.JRadioButton();
        singleStatusRButton = new javax.swing.JRadioButton();
        childrenCountPanel = new javax.swing.JPanel();
        NumberOfMarriedChildren = new javax.swing.JLabel();
        NoOfUnmarriedChildren = new javax.swing.JLabel();
        marriedChildrenCountSpinner = new javax.swing.JSpinner();
        unmarriedChildrenCountSpinner = new javax.swing.JSpinner();
        namenotvalidlabel = new javax.swing.JLabel();
        nicnotvalidlabel = new javax.swing.JLabel();
        annualIncomeText = new javax.swing.JTextField();
        incomenotvalidlabel = new javax.swing.JLabel();
        AnnualIncome = new javax.swing.JLabel();
        Status1 = new javax.swing.JLabel();
        maleRButton = new javax.swing.JRadioButton();
        femaleRButton = new javax.swing.JRadioButton();
        spouseNameText = new javax.swing.JTextField();
        Name1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        landCombo = new javax.swing.JComboBox<>();
        addNewLandButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lotCombo = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        registerButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        permitNumberText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        permitIssueDateText = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lotnolabel = new javax.swing.JLabel();
        sucNoText = new javax.swing.JTextField();
        extentlabel = new javax.swing.JLabel();
        sucNameText = new javax.swing.JTextField();
        sucNicText = new javax.swing.JTextField();
        sucPortionText = new javax.swing.JTextField();
        add_lot_buttun = new javax.swing.JToggleButton();
        extentlabel1 = new javax.swing.JLabel();
        extentlabel2 = new javax.swing.JLabel();
        sucAddressText = new javax.swing.JTextField();
        extentlabel3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lot_table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        personalDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        RegNo.setText("Reg No:");

        Name.setText("Name:");

        NIC.setText("NIC :");

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        nameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextKeyReleased(evt);
            }
        });

        nicText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicTextActionPerformed(evt);
            }
        });
        nicText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicTextKeyReleased(evt);
            }
        });

        Address.setText("Address:");

        addressText.setColumns(20);
        addressText.setRows(5);
        addressText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressTextKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(addressText);

        Status.setText("Status:");

        marriedStatusRButton.setText("Married");
        marriedStatusRButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                marriedStatusRButtonStateChanged(evt);
            }
        });
        marriedStatusRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marriedStatusRButtonActionPerformed(evt);
            }
        });
        marriedStatusRButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                marriedStatusRButtonKeyReleased(evt);
            }
        });

        singleStatusRButton.setText("Single");
        singleStatusRButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                singleStatusRButtonStateChanged(evt);
            }
        });
        singleStatusRButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                singleStatusRButtonKeyReleased(evt);
            }
        });

        childrenCountPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Number of children"));

        NumberOfMarriedChildren.setText("No. of married children:");

        NoOfUnmarriedChildren.setText("No. of  unmarried children:");

        marriedChildrenCountSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                marriedChildrenCountSpinnerStateChanged(evt);
            }
        });
        marriedChildrenCountSpinner.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                marriedChildrenCountSpinnerKeyReleased(evt);
            }
        });

        unmarriedChildrenCountSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                unmarriedChildrenCountSpinnerStateChanged(evt);
            }
        });
        unmarriedChildrenCountSpinner.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unmarriedChildrenCountSpinnerKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout childrenCountPanelLayout = new javax.swing.GroupLayout(childrenCountPanel);
        childrenCountPanel.setLayout(childrenCountPanelLayout);
        childrenCountPanelLayout.setHorizontalGroup(
            childrenCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childrenCountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(childrenCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NoOfUnmarriedChildren, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(NumberOfMarriedChildren, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(childrenCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(marriedChildrenCountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unmarriedChildrenCountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        childrenCountPanelLayout.setVerticalGroup(
            childrenCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childrenCountPanelLayout.createSequentialGroup()
                .addGroup(childrenCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marriedChildrenCountSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(NumberOfMarriedChildren))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(childrenCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unmarriedChildrenCountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoOfUnmarriedChildren)))
        );

        namenotvalidlabel.setForeground(new java.awt.Color(204, 0, 0));
        namenotvalidlabel.setText("Not Valid");

        nicnotvalidlabel.setForeground(new java.awt.Color(204, 0, 0));
        nicnotvalidlabel.setText("Not Valid");

        annualIncomeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                annualIncomeTextKeyReleased(evt);
            }
        });

        incomenotvalidlabel.setForeground(new java.awt.Color(204, 0, 0));
        incomenotvalidlabel.setText("Not Valid");

        AnnualIncome.setText("Estimated Annual Income: Rs.");

        Status1.setText("Gender:");

        maleRButton.setText("Male");
        maleRButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                maleRButtonStateChanged(evt);
            }
        });
        maleRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRButtonActionPerformed(evt);
            }
        });
        maleRButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                maleRButtonKeyReleased(evt);
            }
        });

        femaleRButton.setText("Female");
        femaleRButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                femaleRButtonStateChanged(evt);
            }
        });
        femaleRButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                femaleRButtonKeyReleased(evt);
            }
        });

        spouseNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouseNameTextActionPerformed(evt);
            }
        });
        spouseNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spouseNameTextKeyReleased(evt);
            }
        });

        Name1.setText("Spouse Name:");

        javax.swing.GroupLayout personalDetailPanelLayout = new javax.swing.GroupLayout(personalDetailPanel);
        personalDetailPanel.setLayout(personalDetailPanelLayout);
        personalDetailPanelLayout.setHorizontalGroup(
            personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalDetailPanelLayout.createSequentialGroup()
                        .addComponent(childrenCountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(304, 304, 304))
                    .addGroup(personalDetailPanelLayout.createSequentialGroup()
                        .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personalDetailPanelLayout.createSequentialGroup()
                                .addComponent(AnnualIncome)
                                .addGap(18, 18, 18)
                                .addComponent(annualIncomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(incomenotvalidlabel))
                            .addGroup(personalDetailPanelLayout.createSequentialGroup()
                                .addComponent(Name1)
                                .addGap(23, 23, 23)
                                .addComponent(spouseNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(personalDetailPanelLayout.createSequentialGroup()
                                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RegNo)
                                    .addComponent(NIC)
                                    .addComponent(Name)
                                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(personalDetailPanelLayout.createSequentialGroup()
                                        .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(regNotext, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(personalDetailPanelLayout.createSequentialGroup()
                                                .addComponent(nicText, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(nicnotvalidlabel))
                                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(namenotvalidlabel))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(personalDetailPanelLayout.createSequentialGroup()
                                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Status1)
                                    .addComponent(Status))
                                .addGap(53, 53, 53)
                                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(personalDetailPanelLayout.createSequentialGroup()
                                        .addComponent(marriedStatusRButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(singleStatusRButton))
                                    .addGroup(personalDetailPanelLayout.createSequentialGroup()
                                        .addComponent(maleRButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(femaleRButton)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        personalDetailPanelLayout.setVerticalGroup(
            personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegNo)
                    .addComponent(regNotext, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namenotvalidlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIC)
                    .addComponent(nicText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nicnotvalidlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Address)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Status1)
                    .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(femaleRButton)
                        .addComponent(maleRButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Status)
                    .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(marriedStatusRButton)
                        .addComponent(singleStatusRButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name1)
                    .addComponent(spouseNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(childrenCountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnnualIncome)
                    .addComponent(annualIncomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incomenotvalidlabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lot details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setText("Select land:");

        addNewLandButton.setText("Add New Land");

        jLabel2.setText("Select lot:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(landCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addNewLandButton))
                    .addComponent(lotCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(addNewLandButton)
                    .addComponent(landCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lotCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerButton)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Permit Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel3.setText("Permit Number:");

        permitNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permitNumberTextActionPerformed(evt);
            }
        });

        jLabel4.setText("Issued Date:");

        permitIssueDateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permitIssueDateTextActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nominate Successors", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 11))); // NOI18N

        lotnolabel.setText("Suc. No");

        extentlabel.setText("Name :");

        sucNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucNameTextActionPerformed(evt);
            }
        });
        sucNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sucNameTextKeyReleased(evt);
            }
        });

        sucNicText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucNicTextActionPerformed(evt);
            }
        });
        sucNicText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sucNicTextKeyReleased(evt);
            }
        });

        sucPortionText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucPortionTextActionPerformed(evt);
            }
        });
        sucPortionText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sucPortionTextKeyReleased(evt);
            }
        });

        add_lot_buttun.setText("Add Successor");
        add_lot_buttun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_lot_buttunActionPerformed(evt);
            }
        });
        add_lot_buttun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                add_lot_buttunKeyReleased(evt);
            }
        });

        extentlabel1.setText("NIC :");

        extentlabel2.setText("Portion:");

        sucAddressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucAddressTextActionPerformed(evt);
            }
        });
        sucAddressText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sucAddressTextKeyReleased(evt);
            }
        });

        extentlabel3.setText("Address:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lotnolabel)
                    .addComponent(extentlabel)
                    .addComponent(extentlabel1)
                    .addComponent(extentlabel2)
                    .addComponent(extentlabel3))
                .addGap(49, 49, 49)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(sucAddressText)
                        .addGap(459, 459, 459))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(sucPortionText, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addGap(691, 691, 691))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(sucNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sucNicText, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sucNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(add_lot_buttun, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lotnolabel)
                    .addComponent(sucNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sucNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extentlabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extentlabel1)
                    .addComponent(sucNicText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extentlabel2)
                    .addComponent(sucPortionText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extentlabel3)
                    .addComponent(sucAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(add_lot_buttun, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Added Successors"));

        lot_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SucNo", "Name", "NIC", "Portion", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lot_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(lot_table);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(permitIssueDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(permitNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(permitNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(permitIssueDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout NewApplicantDetailPanelLayout = new javax.swing.GroupLayout(NewApplicantDetailPanel);
        NewApplicantDetailPanel.setLayout(NewApplicantDetailPanelLayout);
        NewApplicantDetailPanelLayout.setHorizontalGroup(
            NewApplicantDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(personalDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        NewApplicantDetailPanelLayout.setVerticalGroup(
            NewApplicantDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewApplicantDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personalDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout newApplicantTabLayout = new javax.swing.GroupLayout(newApplicantTab);
        newApplicantTab.setLayout(newApplicantTabLayout);
        newApplicantTabLayout.setHorizontalGroup(
            newApplicantTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newApplicantTabLayout.createSequentialGroup()
                .addComponent(NewApplicantDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 420, Short.MAX_VALUE))
        );
        newApplicantTabLayout.setVerticalGroup(
            newApplicantTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newApplicantTabLayout.createSequentialGroup()
                .addComponent(NewApplicantDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 101, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(newApplicantTab);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1402, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Add New Application", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 947, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1402, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 947, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1402, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        int isMarried = 1;
        String applicantNumber = regNotext.getText();
        String aplicantName = nameText.getText();
        String nic = nicText.getText();
        String telephoneNumber = telephoneText.getText();
        String address = addressText.getText();
        String DOB = birthdaytext.getText();
        if (singleStatusRButton.isSelected()) {
            isMarried = 0;
        }
        int marriedSons = 0, unmarriedSons = 0;
        double annualincome = 0;
        try {
            marriedSons = Integer.parseInt(marriedChildrenCountSpinner.getValue().toString());
            unmarriedSons = Integer.parseInt(unmarriedChildrenCountSpinner.getValue().toString());
            annualincome = Double.parseDouble(annualIncomeText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "OOps! Something Went Wrong!");

        }

        if (!PatternChecker.checkStringdirect(nameText.getText())) {
            namenotvalidlabel.setVisible(true);
        } else if (!PatternChecker.checkNICdirect(nicText.getText())) {
            nicnotvalidlabel.setVisible(true);
        } else if (!PatternChecker.checkTelNumdirect(telephoneText.getText())) {
            phonenumnotvalidlabel.setVisible(true);
        } else if (!PatternChecker.checkDecimaldirect(annualIncomeText.getText())) {
            incomenotvalidlabel.setVisible(true);
        } else if (birthdaytext.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Birthday Is Not Generated.");
        } else {
            Client client = new Client(regno, nic, aplicantName, DOB, telephoneNumber, address, annualincome, 0, 0, isMarried, marriedSons, unmarriedSons);
            try {
                boolean addNewClient = ClientController.addNewClient(client);
                if (addNewClient) {
                    JOptionPane.showMessageDialog(rootPane, "applicant added successfully");
                    resetFrame();
                }
            } catch (ClassNotFoundException | SQLException | RemoteException ex) {
                Logger.getLogger(ApplicantForm.class.getName()).log(Level.SEVERE, null, ex);

            }
        }

    }//GEN-LAST:event_registerButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void nameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextKeyReleased

        namenotvalidlabel.setVisible(false);
        String newtext = PatternChecker.checkstring(nameText.getText());
        nameText.setText(newtext);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (PatternChecker.checkStringdirect(nameText.getText())) {
                nicText.requestFocus();
            } else {
                namenotvalidlabel.setVisible(true);
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            nicText.requestFocus();
        }
        EnableAddButton();
    }//GEN-LAST:event_nameTextKeyReleased

    private void nicTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicTextActionPerformed

    private void nicTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicTextKeyReleased
        EnableAddButton();

        nicnotvalidlabel.setVisible(false);
        String newtext = PatternChecker.checkNIC(nicText.getText());
        nicText.setText(newtext);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (PatternChecker.checkNICdirect(nicText.getText())) {
                try {
                    Client client = ClientController.searchClient(nicText.getText());
                    if (client != null) {
                        JOptionPane.showMessageDialog(this, "This applicant is already in list", "Invalid Applicant Entry", 2);
                        resetFrame();
                    }
                    telephoneText.requestFocus();
                } catch (ClassNotFoundException | SQLException | RemoteException ex) {
                    Logger.getLogger(ApplicantForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                nicnotvalidlabel.setVisible(true);
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            telephoneText.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            nameText.requestFocus();
        }
    }//GEN-LAST:event_nicTextKeyReleased

    private void addressTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTextKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && addressText.getText().trim().length() != 0) {

            Generate.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            Generate.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            telephoneText.requestFocus();
        }
        EnableAddButton();
    }//GEN-LAST:event_addressTextKeyReleased

    private void marriedStatusRButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_marriedStatusRButtonStateChanged
        // TODO add your handling code here:
        if (marriedStatusRButton.isSelected()) {
            singleStatusRButton.setSelected(false);
        }
        EnableAddButton();
    }//GEN-LAST:event_marriedStatusRButtonStateChanged

    private void marriedStatusRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marriedStatusRButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marriedStatusRButtonActionPerformed

    private void marriedStatusRButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marriedStatusRButtonKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            marriedStatusRButton.isSelected();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            marriedChildrenCountSpinner.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            Generate.requestFocus();

        } else if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            singleStatusRButton.requestFocus();

        }
        EnableAddButton();
    }//GEN-LAST:event_marriedStatusRButtonKeyReleased

    private void singleStatusRButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_singleStatusRButtonStateChanged
        // TODO add your handling code here:
        if (singleStatusRButton.isSelected()) {
            marriedStatusRButton.setSelected(false);
        }
        EnableAddButton();
    }//GEN-LAST:event_singleStatusRButtonStateChanged

    private void singleStatusRButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_singleStatusRButtonKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            singleStatusRButton.isSelected();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            annualIncomeText.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            Generate.requestFocus();

        } else if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            marriedStatusRButton.requestFocus();

        }
        EnableAddButton();
    }//GEN-LAST:event_singleStatusRButtonKeyReleased

    private void marriedChildrenCountSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_marriedChildrenCountSpinnerStateChanged
        // TODO add your handling code here:
        GUIitemsValidator.limitminimumSpinnerValue(marriedChildrenCountSpinner, 0);
    }//GEN-LAST:event_marriedChildrenCountSpinnerStateChanged

    private void marriedChildrenCountSpinnerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marriedChildrenCountSpinnerKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            unmarriedChildrenCountSpinner.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            GUIitemsValidator.decrementSpinnerValue(marriedChildrenCountSpinner);
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            GUIitemsValidator.incermentSpinnerValue(marriedChildrenCountSpinner);

        }
    }//GEN-LAST:event_marriedChildrenCountSpinnerKeyReleased

    private void unmarriedChildrenCountSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_unmarriedChildrenCountSpinnerStateChanged
        // TODO add your handling code here:
        GUIitemsValidator.limitminimumSpinnerValue(unmarriedChildrenCountSpinner, 0);
    }//GEN-LAST:event_unmarriedChildrenCountSpinnerStateChanged

    private void unmarriedChildrenCountSpinnerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unmarriedChildrenCountSpinnerKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            registerButton.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            GUIitemsValidator.decrementSpinnerValue(unmarriedChildrenCountSpinner);
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            GUIitemsValidator.incermentSpinnerValue(unmarriedChildrenCountSpinner);

        }
    }//GEN-LAST:event_unmarriedChildrenCountSpinnerKeyReleased

    private void annualIncomeTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_annualIncomeTextKeyReleased
        // TODO add your handling code here:
        incomenotvalidlabel.setVisible(false);
        String newtext = PatternChecker.checkDecimal(annualIncomeText.getText());
        annualIncomeText.setText(newtext);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (PatternChecker.checkDecimaldirect(annualIncomeText.getText())) {
                unmarriedChildrenCountSpinner.requestFocus();
            } else {
                incomenotvalidlabel.setVisible(true);
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            unmarriedChildrenCountSpinner.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            marriedStatusRButton.requestFocus();

        }
        EnableAddButton();
    }//GEN-LAST:event_annualIncomeTextKeyReleased

    private void maleRButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_maleRButtonStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRButtonStateChanged

    private void maleRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRButtonActionPerformed

    private void maleRButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maleRButtonKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRButtonKeyReleased

    private void femaleRButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_femaleRButtonStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRButtonStateChanged

    private void femaleRButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_femaleRButtonKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRButtonKeyReleased

    private void spouseNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouseNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseNameTextActionPerformed

    private void spouseNameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spouseNameTextKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseNameTextKeyReleased

    private void permitNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permitNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_permitNumberTextActionPerformed

    private void permitIssueDateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permitIssueDateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_permitIssueDateTextActionPerformed

    private void sucNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sucNameTextActionPerformed

    private void sucNameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sucNameTextKeyReleased
        // TODO add your handling code here:
        if (sucNameText.getText().trim().length() != 0 && sucNicText.getText().trim().length() != 0 && sucPortionText.getText().trim().length() != 0) {
            add_lot_buttun.setEnabled(true);
        }
        if (sucNameText.getText().trim().length() == 0 || sucNicText.getText().trim().length() == 0 || sucPortionText.getText().trim().length() == 0) {
            add_lot_buttun.setEnabled(false);
        }
        acresnotvalidlabel.setVisible(false);
        String newtext = PatternChecker.checkDecimal(sucNameText.getText());
        sucNameText.setText(newtext);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (PatternChecker.checkDecimaldirect(sucNameText.getText())) {
                sucNicText.requestFocus();
            } else {
                acresnotvalidlabel.setVisible(true);
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            sucNicText.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            land_south_test.requestFocus();
        }
    }//GEN-LAST:event_sucNameTextKeyReleased

    private void sucNicTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucNicTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sucNicTextActionPerformed

    private void sucNicTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sucNicTextKeyReleased
        // TODO add your handling code here:
        if (sucNameText.getText().trim().length() != 0 && sucNicText.getText().trim().length() != 0 && sucPortionText.getText().trim().length() != 0) {
            add_lot_buttun.setEnabled(true);
        }
        if (sucNameText.getText().trim().length() == 0 || sucNicText.getText().trim().length() == 0 || sucPortionText.getText().trim().length() == 0) {
            add_lot_buttun.setEnabled(false);
        }
        perchesnotvalidlabel.setVisible(false);
        String newtext = PatternChecker.checkDecimal(sucNicText.getText());
        sucNicText.setText(newtext);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (PatternChecker.checkDecimaldirect(sucNicText.getText())) {
                sucPortionText.requestFocus();
            } else {
                perchesnotvalidlabel.setVisible(true);
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            sucPortionText.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            sucNameText.requestFocus();
        }
    }//GEN-LAST:event_sucNicTextKeyReleased

    private void sucPortionTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucPortionTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sucPortionTextActionPerformed

    private void sucPortionTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sucPortionTextKeyReleased
        // TODO add your handling code here:
        if (sucNameText.getText().trim().length() != 0 && sucNicText.getText().trim().length() != 0 && sucPortionText.getText().trim().length() != 0) {
            add_lot_buttun.setEnabled(true);
        }
        if (sucNameText.getText().trim().length() == 0 || sucNicText.getText().trim().length() == 0 || sucPortionText.getText().trim().length() == 0) {
            add_lot_buttun.setEnabled(false);
        }
        roodsnotvalidlabel.setVisible(false);
        String newtext = PatternChecker.checkDecimal(sucPortionText.getText());
        sucPortionText.setText(newtext);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (PatternChecker.checkDecimaldirect(sucPortionText.getText())) {
                add_lot_buttun.requestFocus();
            } else {
                perchesnotvalidlabel.setVisible(true);
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            add_lot_buttun.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            sucNicText.requestFocus();
        }
    }//GEN-LAST:event_sucPortionTextKeyReleased

    private void add_lot_buttunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_lot_buttunActionPerformed

        DefaultTableModel tableModel = (DefaultTableModel) lot_table.getModel();
        Object[] rawdata = {sucNoText.getText(), sucNameText.getText(), sucNicText.getText(), sucPortionText.getText()};
        tableModel.addRow(rawdata);
        sucNameText.setText("");
        sucNicText.setText("");
        sucPortionText.setText("");
        sucNoText.setText(IdGenerator.generateNextLotNumber(sucNoText.getText()));
        add_lot_buttun.setEnabled(false);
    }//GEN-LAST:event_add_lot_buttunActionPerformed

    private void add_lot_buttunKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_add_lot_buttunKeyReleased
        // TODO add your handling code here
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            sucPortionText.requestFocus();
        }
    }//GEN-LAST:event_add_lot_buttunKeyReleased

    private void sucAddressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucAddressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sucAddressTextActionPerformed

    private void sucAddressTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sucAddressTextKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sucAddressTextKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel AnnualIncome;
    private javax.swing.JLabel NIC;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Name1;
    private javax.swing.JPanel NewApplicantDetailPanel;
    private javax.swing.JLabel NoOfUnmarriedChildren;
    private javax.swing.JLabel NumberOfMarriedChildren;
    private javax.swing.JLabel RegNo;
    private javax.swing.JLabel Status;
    private javax.swing.JLabel Status1;
    private javax.swing.JButton addNewLandButton;
    private javax.swing.JToggleButton add_lot_buttun;
    private javax.swing.JTextArea addressText;
    private javax.swing.JTextField annualIncomeText;
    private javax.swing.JPanel childrenCountPanel;
    private javax.swing.JLabel extentlabel;
    private javax.swing.JLabel extentlabel1;
    private javax.swing.JLabel extentlabel2;
    private javax.swing.JLabel extentlabel3;
    private javax.swing.JRadioButton femaleRButton;
    private javax.swing.JLabel incomenotvalidlabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> landCombo;
    private javax.swing.JComboBox<String> lotCombo;
    private javax.swing.JTable lot_table;
    private javax.swing.JLabel lotnolabel;
    private javax.swing.JRadioButton maleRButton;
    private javax.swing.JSpinner marriedChildrenCountSpinner;
    private javax.swing.JRadioButton marriedStatusRButton;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel namenotvalidlabel;
    private javax.swing.JPanel newApplicantTab;
    private javax.swing.JTextField nicText;
    private javax.swing.JLabel nicnotvalidlabel;
    private javax.swing.JTextField permitIssueDateText;
    private javax.swing.JTextField permitNumberText;
    private javax.swing.JPanel personalDetailPanel;
    private javax.swing.JTextField regNotext;
    private javax.swing.JButton registerButton;
    private javax.swing.JRadioButton singleStatusRButton;
    private javax.swing.JTextField spouseNameText;
    private javax.swing.JTextField sucAddressText;
    private javax.swing.JTextField sucNameText;
    private javax.swing.JTextField sucNicText;
    private javax.swing.JTextField sucNoText;
    private javax.swing.JTextField sucPortionText;
    private javax.swing.JSpinner unmarriedChildrenCountSpinner;
    // End of variables declaration//GEN-END:variables
}
